### PR TITLE
Fix description of Meade command parameters

### PR DESCRIPTION
**Pull request by JakobPetersson**
After using/reading through the Meade command documentation  I have a very small fix.

### CODE REVIEW

**Comment by anjok** [comment]
You also need to fix the utc offset

**Comment by JakobPetersson** [comment]
> You also need to fix the utc offset

I am unsure of what related documentation of UTC offset you mean could be fixed at the same time. Can you clarify?

Edit: I understand which change you mean. But that appears to be an incorrect implementation of the protocol, and should be handled as a separate issue. Unrelated to this small fix.

**Comment by ClutchplateDude** [comment]
> > You also need to fix the utc offset
> 
> I am unsure of what related documentation of UTC offset you mean could be fixed at the same time. Can you clarify?
> 
> Edit: I understand which change you mean. But that appears to be an incorrect implementation of the protocol, and should be handled as a separate issue. Unrelated to this small fix.

You don't *NEED* to fix anything, Jakob. Just submit what you feel comfortable with and that helps with the code base.

**Comment by JakobPetersson** [comment]
> You don't _NEED_ to fix anything, Jakob. Just submit what you feel comfortable with and that helps with the code base.

You don't have to worry @ClutchplateDude :) Thank you for checking in on this PR.

Should we keep the PR going?
Merge it?
Or move these changes into #180?

**Comment by JakobPetersson** [comment]
Fixes included in #181, closing.

**Pull request closed without merging**
